[package]

name = "8008"
description = "A simple drum machine."
version = "0.0.0"
authors = ["jj <jj.weber@gmail.com>"]
readme = "README.md"
keywords = ["synthesis", "dsp", "audio", "music", "instrument"]
license = "MIT"
repository = "https://github.com/zjjw/rust-8008.git"
homepage = "https://github.com/zjjw/rust-8008"


[dependencies]
synth = "0.9.2"
dsp-chain = "0.11.0"
envelope = "0.6.3"
mindtree_utils = "0.3.0"
num = "0.1.29"
panning = "0.1.1"
pitch_calc = "0.9.7"
rand = "0.3.11"
rustc-serialize = "0.3.16"
simple_gaussian = "0.4.4"
time_calc = "0.10.0"

[dev-dependencies]
portaudio = "0.6.2"
